<template>
  <div class="relative group">
    <div class="absolute -inset-0.5 bg-gradient-to-r from-cyan-500 to-blue-600 rounded-lg blur opacity-30 group-hover:opacity-100 transition duration-1000 group-hover:duration-200"></div>
    <div class="relative bg-slate-900/80 backdrop-blur-lg rounded-lg p-4 md:p-6 border border-cyan-500/10">
      <!-- Header -->
      <div class="flex items-center justify-between mb-4">
        <h2 class="text-lg md:text-xl font-semibold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
          Route Analysis
        </h2>
        <button
          v-if="currentAnalysis"
          @click="clearAnalysis"
          class="text-xs text-slate-400 hover:text-cyan-400 transition-colors"
        >
          Clear
        </button>
      </div>

      <!-- Loading State -->
      <div v-if="analyzing" class="py-8 text-center">
        <div class="w-8 h-8 border-2 border-cyan-500 border-t-transparent rounded-full animate-spin mx-auto mb-3"></div>
        <span class="text-sm text-slate-400">AI analyzing route...</span>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="py-4 text-center">
        <div class="text-red-400 text-sm mb-2 font-medium">{{ error }}</div>
        <div v-if="errorDetails" class="text-xs text-slate-400 mb-3 mt-2 px-3 py-2 bg-slate-800/50 rounded-lg text-left">
          <div class="font-semibold text-slate-300 mb-1">Details:</div>
          <div class="text-slate-400 break-words">{{ errorDetails }}</div>
        </div>
        <button
          @click="retryAnalysis"
          class="text-xs text-cyan-400 hover:text-cyan-300 transition-colors px-3 py-1.5 rounded-lg border border-cyan-500/20 hover:bg-cyan-500/10"
        >
          Retry Analysis
        </button>
      </div>

      <!-- Analysis Content -->
      <div v-else-if="currentAnalysis" class="space-y-4">
        <div class="bg-slate-800/50 rounded-lg p-4 border border-cyan-500/20">
          <div class="flex items-center gap-2 mb-3">
            <div class="w-2 h-2 rounded-full bg-cyan-400 animate-pulse"></div>
            <span class="text-sm font-semibold text-cyan-300">AI Analysis</span>
            <span class="text-xs text-slate-400 ml-auto">
              Route {{ currentAnalysis.routeIndex + 1 }}
            </span>
          </div>
          <p class="text-sm text-slate-200 leading-relaxed whitespace-pre-wrap">
            {{ currentAnalysis.analysis }}
          </p>
        </div>

        <!-- Analysis Metadata -->
        <div class="flex items-center justify-between text-xs text-slate-400">
          <span>Generated by Gemini 1.5 Flash</span>
          <span>{{ formatTimestamp(currentAnalysis.timestamp) }}</span>
        </div>
      </div>

      <!-- Empty State -->
      <div v-else class="py-8 text-center">
        <div class="w-12 h-12 mx-auto mb-3 rounded-full bg-cyan-500/10 flex items-center justify-center">
          <svg class="w-6 h-6 text-cyan-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
          </svg>
        </div>
        <p class="text-sm text-slate-400">
          Select a route to see AI-powered safety analysis
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { watch, nextTick } from 'vue'
import { useRouteAnalysis } from '~/composables/useRouteAnalysis'

interface Props {
  routeIndex: number | null
  route: any | null
  allRoutes: any[]
}

const props = defineProps<Props>()

const { analyzing, currentAnalysis, error, errorDetails, analyzeRoute, clearAnalysis: clearRouteAnalysis } = useRouteAnalysis()

// Helper function to trigger route analysis
async function triggerRouteAnalysis() {
  console.log('[RouteAnalysis] triggerRouteAnalysis called:', {
    routeIndex: props.routeIndex,
    hasRoute: !!props.route,
    routesLength: props.allRoutes.length,
    route: props.route ? {
      riskScore: props.route.riskScore,
      distance: props.route.distance,
      hotspotsAvoided: props.route.hotspotsAvoided,
      hasHotspotsNearby: Array.isArray(props.route.hotspotsNearby)
    } : null
  })

  if (props.routeIndex === null) {
    console.log('[RouteAnalysis] No route index selected')
    return
  }

  if (!props.route) {
    console.warn('[RouteAnalysis] Route data is not available for index:', props.routeIndex)
    return
  }

  if (props.allRoutes.length === 0) {
    console.warn('[RouteAnalysis] No routes available')
    return
  }

  try {
    // Check if we already have analysis for this route index
    if (currentAnalysis.value?.routeIndex === props.routeIndex) {
      console.log('[RouteAnalysis] Analysis already exists for route index:', props.routeIndex)
      return // Already analyzed
    }
    
    console.log('[RouteAnalysis] Starting route analysis for index:', props.routeIndex)
    await nextTick() // Ensure DOM is updated
    await analyzeRoute(props.route, props.routeIndex, props.allRoutes)
    console.log('[RouteAnalysis] Route analysis completed for index:', props.routeIndex)
  } catch (error) {
    console.error('[RouteAnalysis] Error analyzing route:', error)
  }
}

// Watch for route index changes - triggers analysis when route is selected
watch(
  () => props.routeIndex,
  async (newIndex, oldIndex) => {
    // Clear analysis if route is deselected
    if (newIndex === null) {
      if (oldIndex !== null) {
        clearRouteAnalysis()
      }
      return
    }
    
    // Trigger analysis when route index changes
    if (newIndex !== oldIndex) {
      // Wait a bit for route data to be available
      await nextTick()
      // Try to trigger analysis - if route data isn't ready, the route watch will handle it
      await triggerRouteAnalysis()
    }
  },
  { immediate: true }
)

// Watch for route data changes - triggers analysis when route becomes available
watch(
  () => props.route,
  async (newRoute) => {
    // Only analyze if we have a selected route and route data is available
    if (props.routeIndex !== null && newRoute && props.allRoutes.length > 0) {
      // Check if we need to analyze (no current analysis or different route)
      if (!currentAnalysis.value || currentAnalysis.value.routeIndex !== props.routeIndex) {
        await nextTick()
        await triggerRouteAnalysis()
      }
    }
  },
  { immediate: true, deep: true }
)

// Watch for when routes are loaded - trigger analysis if route is already selected
watch(
  () => props.allRoutes.length,
  async (newLength, oldLength) => {
    // If routes were just loaded and we have a selected route, trigger analysis
    if (newLength > 0 && props.routeIndex !== null && props.route) {
      if (oldLength === 0 || !currentAnalysis.value || currentAnalysis.value.routeIndex !== props.routeIndex) {
        await nextTick()
        await triggerRouteAnalysis()
      }
    }
  }
)

function clearAnalysis() {
  clearRouteAnalysis()
}

async function retryAnalysis() {
  if (props.routeIndex !== null && props.route && props.allRoutes.length > 0) {
    await analyzeRoute(props.route, props.routeIndex, props.allRoutes)
  }
}

function formatTimestamp(timestamp: string): string {
  try {
    const date = new Date(timestamp)
    const now = new Date()
    const diffMs = now.getTime() - date.getTime()
    const diffMins = Math.floor(diffMs / (1000 * 60))
    
    if (diffMins < 1) return 'Just now'
    if (diffMins < 60) return `${diffMins}m ago`
    
    const diffHours = Math.floor(diffMins / 60)
    if (diffHours < 24) return `${diffHours}h ago`
    
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
  } catch {
    return ''
  }
}
</script>

<style scoped>
.whitespace-pre-wrap {
  white-space: pre-wrap;
  word-wrap: break-word;
}
</style>

